### ISSUE TITLE
is the class can be used for nominet epp server ?

### ISSUE THREAD

**Issue by naja7host** [AfriCC/php-epp2#53]
Nominet use the ep server, is the class can be used for nominet epp server ?

**Comment by lifeofguenter** [comment]
Sure, why not?

**Comment by naja7host** [comment]
every time i get a error

Timeout while reading from EPP Server [1;31m� ddfdfd-596cc9ce0035a [0m
Warning: unpack(): Type N: not enough input, need 4, have 0 

Fatal error: Uncaught exception 'Exception' with message 'Got a bad frame header length of 0 bytes from peer' in /home/dfdfdfd/public_html/test/AfriCC/EPP/Client.php:200

**Comment by hassanchakroun** [comment]
Hi naja7host,
Could you share you snippet of code ?
I have a problem too, see https://stackoverflow.com/questions/46316978/php-socket-using-symantec-certificate-without-a-private-key

**Comment by domainregistrar** [comment]
Be sure to enable ssl for the connection, I had this response too before I added that :)

**Comment by johnny-bit** [comment]
Just to be sure - in order to have full and properly working connection you need to properly configure certificates for connection. Make sure you properly put path to private key file in `pk_cert` option, path to certificate file in `local_cert` option, and path to CA chain in `ca_cert` option.

If you have connection issues, make sure that all registrar requirements are met. If they are and you still have problems - feel free to open another issue and describe problem in detail
